### ISSUE TITLE
Feature: App icon + logo

### ISSUE THREAD

**Issue by EduM22** [iOS-Development-Group-P/iOS-quiz#13]
Create an icon + logo to be used in the app

**Comment by ZyntaaX** [comment]
Created a temporary prototype logo for the application

**Comment by ZyntaaX** [comment]
Created a temporary prototype icon for the application:

<img src="https://github.com/iOS-Development-Group-P/iOS-quiz/blob/development/planning/assets/icon/app-icon-prototype-rounded.png?raw=true">
